name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-26
    steps:
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: '26.5'
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore workloads
      run: dotnet workload restore
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -r iossimulator-arm64
    - name: Test
      run: dotnet test JamSeshun.Tests/JamSeshun.Tests.csproj --no-build --verbosity normal
